"""
D-ID Talking Avatar Video Service
Generates realistic AI presenter videos for the Individual Learner role.

Flow:
  1. Receive a text script (already generated by GPT via generate_teacher_dialogue or TTS pipeline)
  2. POST to D-ID /talks endpoint with a stock presenter + the script text (TTS handled by D-ID)
  3. Poll GET /talks/{id} until status == 'done' (usually 30-90 seconds)
  4. Return the result_url (public mp4 URL)

Get a free D-ID API key at: https://www.d-id.com/
Set env var: DID_API_KEY=your_key_here
"""

import os
import time
import logging
import hashlib
import json
import base64
import requests

logger = logging.getLogger(__name__)

DID_API_KEY = os.getenv("DID_API_KEY", "")
DID_API_EMAIL = os.getenv("DID_API_EMAIL", "")  # your D-ID account email
DID_BASE_URL = "https://api.d-id.com"


def _get_auth_header() -> str:
    """
    D-ID uses HTTP Basic Auth.
    Key formats supported:
      1. Key already starts with 'Basic ' → use directly (from D-ID dashboard copy)
      2. Key contains ':' → already email:key, base64-encode as-is
      3. DID_API_EMAIL is set → combine as email:key then base64-encode
      4. Fallback → base64-encode the raw key alone
    """
    key = DID_API_KEY.strip()
    # Case 1: Dashboard gives 'Basic <base64>' — use directly
    if key.lower().startswith("basic "):
        return key
    # Case 2: key already in email:key plain-text format
    if ":" in key:
        encoded = base64.b64encode(key.encode()).decode()
    # Case 3: combine email + key
    elif DID_API_EMAIL:
        encoded = base64.b64encode(f"{DID_API_EMAIL}:{key}".encode()).decode()
    else:
        # Fallback: encode key alone
        encoded = base64.b64encode(key.encode()).decode()
    return f"Basic {encoded}"

# ── Stock D-ID presenter avatars — professional, diverse ──
# source_url must be a publicly accessible face image accepted by D-ID /talks.
# Using D-ID's own public bucket images (verified working) and clips-presenters CDN.
PROFESSIONAL_PRESENTERS = [
    {
        "id": "amy",
        "name": "Amy",
        "source_url": "https://d-id-public-bucket.s3.us-east-1.amazonaws.com/alice.jpg",  # female
        "voice": {"type": "microsoft", "voice_id": "en-US-JennyNeural"},
    },
    {
        "id": "daniel",
        "name": "Daniel",
        "source_url": "https://d-id-public-bucket.s3.us-east-1.amazonaws.com/or-roman.jpg",  # male
        "voice": {"type": "microsoft", "voice_id": "en-US-GuyNeural"},
    },
    {
        "id": "noelle",
        "name": "Noelle",
        "source_url": "https://d-id-public-bucket.s3.us-east-1.amazonaws.com/alice.jpg",  # female
        "voice": {"type": "microsoft", "voice_id": "en-US-AriaNeural"},
    },
    {
        "id": "william",
        "name": "William",
        "source_url": "https://d-id-public-bucket.s3.us-east-1.amazonaws.com/or-roman.jpg",  # male
        "voice": {"type": "microsoft", "voice_id": "en-US-ChristopherNeural"},
    },
]


def _pick_presenter(topic: str) -> dict:
    """Pick a consistent presenter based on topic name (same topic → same face)."""
    h = int(hashlib.md5(topic.encode()).hexdigest(), 16)
    return PROFESSIONAL_PRESENTERS[h % len(PROFESSIONAL_PRESENTERS)]


def _did_cache_key(topic: str, doc_name: str, language: str) -> str:
    raw = f"{topic}|{doc_name}|{language}"
    return hashlib.md5(raw.encode()).hexdigest()


# ── In-memory cache: key → {video_url, talk_id, status, created_at} ──
_did_mem_cache: dict = {}
DID_CACHE_TTL = 86400 * 7  # 7 days


def get_cached_did_video(topic: str, doc_name: str, language: str) -> dict | None:
    """Return cached D-ID video dict if still valid, else None."""
    key = _did_cache_key(topic, doc_name, language)
    entry = _did_mem_cache.get(key)
    if entry and (time.time() - entry.get("ts", 0)) < DID_CACHE_TTL:
        return entry["data"]
    return None


def cache_did_video(topic: str, doc_name: str, language: str, data: dict):
    key = _did_cache_key(topic, doc_name, language)
    _did_mem_cache[key] = {"data": data, "ts": time.time()}


def create_did_talk(script: str, topic: str, language: str = "en") -> dict:
    """
    Submit a D-ID /talks job with a text script.

    Returns:
        {"id": "tlk_xxx", "status": "created"}
    Raises:
        ValueError if DID_API_KEY not set
        requests.HTTPError on API error
    """
    if not DID_API_KEY:
        raise ValueError("DID_API_KEY environment variable is not set. "
                         "Get a free key at https://www.d-id.com/")

    presenter = _pick_presenter(topic)

    # Truncate script to D-ID's limit (~4000 chars per talk)
    script_text = script[:4000].strip()

    # Language → Microsoft Azure voice mapping
    voice_id = presenter["voice"]["voice_id"]  # default en-US
    if language == "ta":
        voice_id = "ta-IN-PallaviNeural"
    elif language == "hi":
        voice_id = "hi-IN-SwaraNeural"
    elif language == "de":
        voice_id = "de-DE-KatjaNeural"
    elif language == "fr":
        voice_id = "fr-FR-DeniseNeural"
    elif language == "es":
        voice_id = "es-ES-ElviraNeural"

    payload = {
        "source_url": presenter["source_url"],
        "script": {
            "type": "text",
            "input": script_text,
            "provider": {
                "type": "microsoft",
                "voice_id": voice_id,
            },
        },
        "config": {
            "fluent": True,
            "pad_audio": 0.0,
            "result_format": "mp4",
        },
    }

    headers = {
        "Authorization": _get_auth_header(),
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    logger.info(f"📽️ D-ID: submitting talk for '{topic}' ({len(script_text)} chars)")
    response = requests.post(
        f"{DID_BASE_URL}/talks",
        headers=headers,
        json=payload,
        timeout=30,
    )
    response.raise_for_status()
    data = response.json()
    logger.info(f"✅ D-ID talk submitted: {data.get('id')}")
    return data


def poll_did_talk(talk_id: str, max_wait: int = 180, interval: int = 5) -> dict:
    """
    Poll D-ID GET /talks/{id} until status is 'done' or 'error'.

    Returns the full talk object with 'result_url' when ready.
    Raises TimeoutError if max_wait exceeded.
    """
    if not DID_API_KEY:
        raise ValueError("DID_API_KEY environment variable is not set.")

    headers = {
        "Authorization": _get_auth_header(),
        "Accept": "application/json",
    }

    deadline = time.time() + max_wait
    while time.time() < deadline:
        resp = requests.get(
            f"{DID_BASE_URL}/talks/{talk_id}",
            headers=headers,
            timeout=15,
        )
        resp.raise_for_status()
        data = resp.json()
        status = data.get("status", "")
        logger.info(f"🔄 D-ID poll {talk_id}: status={status}")

        if status == "done":
            return data
        elif status == "error":
            raise RuntimeError(f"D-ID rendering failed: {data.get('error', {})}")

        time.sleep(interval)

    raise TimeoutError(f"D-ID talk {talk_id} did not finish within {max_wait}s")


def generate_did_video_sync(script: str, topic: str, doc_name: str = "", language: str = "en") -> dict:
    """
    Full synchronous pipeline: submit + poll + return result.
    Suitable for running inside asyncio.run_in_executor.

    Returns:
        {
            "video_url": "https://...",
            "talk_id": "tlk_xxx",
            "presenter": "Amy",
            "cached": False,
        }
    """
    # Check in-memory cache first
    cached = get_cached_did_video(topic, doc_name, language)
    if cached:
        logger.info(f"🎯 D-ID cache HIT: {topic}")
        return {**cached, "cached": True}

    # Submit
    submit_data = create_did_talk(script, topic, language)
    talk_id = submit_data["id"]

    # Poll until done
    result = poll_did_talk(talk_id)
    video_url = result.get("result_url", "")

    if not video_url:
        raise RuntimeError("D-ID returned no result_url after completion")

    presenter = _pick_presenter(topic)
    output = {
        "video_url": video_url,
        "talk_id": talk_id,
        "presenter": presenter["name"],
        "cached": False,
    }

    # Save to memory cache
    cache_did_video(topic, doc_name, language, output)
    logger.info(f"✅ D-ID video ready: {video_url}")
    return output
